// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"
	logic2 "go-zero-demo/server/rpc/user/rpc/internal/logic"
	"go-zero-demo/server/rpc/user/rpc/internal/svc"
	user2 "go-zero-demo/server/rpc/user/rpc/pb/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user2.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Login(ctx context.Context, in *user2.LoginReq) (*user2.LoginResp, error) {
	l := logic2.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) CheckLoginStatus(ctx context.Context, in *user2.CheckLoginStatusReq) (*user2.CheckLoginStatusResp, error) {
	l := logic2.NewCheckLoginStatusLogic(ctx, s.svcCtx)
	return l.CheckLoginStatus(in)
}
