// Code generated by goctl. DO NOT EDIT.
// Source: item.proto

package server

import (
	"context"

	"go-zero-demo/server/rpc/item/internal/logic"
	"go-zero-demo/server/rpc/item/internal/svc"
	"go-zero-demo/server/rpc/item/pb/item"
)

type ItemServer struct {
	svcCtx *svc.ServiceContext
	item.UnimplementedItemServer
}

func NewItemServer(svcCtx *svc.ServiceContext) *ItemServer {
	return &ItemServer{
		svcCtx: svcCtx,
	}
}

func (s *ItemServer) CreateUploadTask(ctx context.Context, in *item.CreateUploadTaskReq) (*item.CreateUploadTaskResp, error) {
	l := logic.NewCreateUploadTaskLogic(ctx, s.svcCtx)
	return l.CreateUploadTask(in)
}

func (s *ItemServer) GetVideoById(ctx context.Context, in *item.GetVideoByIdReq) (*item.GetVideoByIdResp, error) {
	l := logic.NewGetVideoByIdLogic(ctx, s.svcCtx)
	return l.GetVideoById(in)
}
