// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"go-zero-demo/server/rpc/user/internal/logic"
	"go-zero-demo/server/rpc/user/internal/svc"
	"go-zero-demo/server/rpc/user/pb/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Login(ctx context.Context, in *user.LoginReq) (*user.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) Logout(ctx context.Context, in *user.LoginReq) (*user.LogoutResp, error) {
	l := logic.NewLogoutLogic(ctx, s.svcCtx)
	return l.Logout(in)
}

func (s *UserServer) CheckLoginStatus(ctx context.Context, in *user.CheckLoginStatusReq) (*user.CheckLoginStatusResp, error) {
	l := logic.NewCheckLoginStatusLogic(ctx, s.svcCtx)
	return l.CheckLoginStatus(in)
}

func (s *UserServer) GetCurrentUser(ctx context.Context, in *user.GetCurrentUseReq) (*user.GetCurrentUserResp, error) {
	l := logic.NewGetCurrentUserLogic(ctx, s.svcCtx)
	return l.GetCurrentUser(in)
}
