// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"go-zero-demo/user/api/internal/svc"
	"net/http"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/info/:id",
				Handler: getUserInfoHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthorizeHandler},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/user/info/current",
					Handler: getCurrentUserInfoHandler(serverCtx),
				},
			}...,
		),
	)
}
