// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"
	"go-zero-demo/user/rpc/internal/logic"
	"go-zero-demo/user/rpc/internal/svc"
	user2 "go-zero-demo/user/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user2.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Ping(ctx context.Context, in *user2.Request) (*user2.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
