// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Token    string `json:"token"`
}

type GetUserByIdReq struct {
	Id int64 `path:"id"`
}

type GetCurrentUserReq struct {
	Id int64 `path:"id"`
}

type GetCurrentUserResp struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Nickname string `json:"nickname"`
	Gender   string `json:"gender"`
	Mobile   string `json:"mobile"`
}

type GetUserByIdResp struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Nickname string `json:"nickname"`
	Gender   string `json:"gender"`
	Mobile   string `json:"mobile"`
}

type GetShortUrlByIdReq struct {
	Id int64 `path:"id"`
}

type CreateShortUrlReq struct {
	OriginalUrl string `json:"originalUrl"`
}

type CreateShorUrlResp struct {
}

type RedirectShorUrlReq struct {
	ShortUrl string `json:"shortUrl"`
}

type RedirectShorUrlResp struct {
	OriginalUrl string `json:"originalUrl"`
}

type GetTitleByUrlReq struct {
	Url string `form:"url"`
}

type GetTitleByUrlResp struct {
	Title string `json:"title"`
}

type CreateUplaodTaskReq struct {
	Type string `json:"type,options=[video,cover,avatar]"`
}

type CreateUploadTaskResp struct {
	UploadToken string `json:"uploadToken"`
	FileAddr    string `json:"fileAddr"`
}
