// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	shorturl "go-zero-demo/server/api/internal/handler/shorturl"
	user "go-zero-demo/server/api/internal/handler/user"
	"go-zero-demo/server/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/info/:id",
				Handler: user.GetUserInfoHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.LoginStatus, serverCtx.Authorize},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/info/current",
					Handler: user.GetCurrentUserInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/logout",
					Handler: user.LogoutHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.LoginStatus, serverCtx.Authorize},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: shorturl.GetShortUrlByIdHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: shorturl.CreateShortUrlHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/short-url"),
	)
}
